server:
  port: 8080

spring:
  profiles:
    active: dev

---
config:
  activate:
    on-profile: dev

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devMarvelDB?useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
    database: mysql

  sql:
    init:
      platform: mysql
      mode: always


integration:
  marvel:
    public-key: 927377dbe8d9a2788fc038556412d78f
    private-key: f9fd8042fd7dff9c31282d7758e458b4692b05ad
    base-path: http://gateway.marvel.com/v1/public

security:
  jwt:
    secret-key: "ASDOHASODHASODHASHD1023W12DHB102312NDOHUJASIODH12HEJHNADSLDJN123HJKLASDH"
    expiration-minute: 30