server:
  port: 8080

spring:
  profiles:
    active: dev

---
config:
  activate:
    on-profile: dev
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devMarvelDB?useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql

integration:
  marvel:
    public-key: 927377dbe8d9a2788fc038556412d78f
    private-key: f9fd8042fd7dff9c31282d7758e458b4692b05ad
    base-path: http://gateway.marvel.com/v1/public